apiVersion: apps/v1
kind: Deployment
metadata:
  name: apix-deployment
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      component: apix
  template:
    metadata:
      name: argoapix
      labels:
        component: apix
        tier: api
    spec:
      containers:
        - name: argoapix
          image: "{{ .Values.apix.repository }}:{{ .Values.apix.tag }}"
          imagePullPolicy: Always
          env:
          - name: NODE_OPTIONS
            value: --max_old_space_size=2048
          resources:
            requests:
              memory: "0Gi"
              cpu: "0m"
            limits:
              memory: {{ .Values.apix.memory }}
              cpu: {{ .Values.apix.cpu }}
          startupProbe:
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 5
            httpGet:
              path: /profiles/overview
              port: 8080
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: tier
                  operator: In
                  values:
                  - api
                  - db
              topologyKey: kubernetes.io/hostname
